# yamllint disable-file
# Answer file maintained by Copier for: https://github.com/KyleKing/calcipy_template
# Check into version control. Edit by re-running copier and changing responses to the questions
_src_path: /Users/kyleking/Developer/packages/calcipy_template/package_template

