---
name: Bump Version

# FYI: Requires Personal Access Token. See README

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  workflow_dispatch:

defaults:
  run:
    shell: bash

# Could be cool to allow manual specification of the version,
#   but cz doesn't support manual versioning
# The SemVer input could be validated in bash like this:
#   if [[ -n $(egrep -o "^[0-9]+\.[0-9]+\.[0-9]+([abr]c?[0-9])?$" <<< $VALUE) ]]; then ... fi

jobs:
  bump-version:
    # Ignore the commits from this action
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: Bump version and make release with commitizen
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          branch: main
          changelog_increment_filename: body.md
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: body.md
          tag_name: ${{ env.REVISION }}
