---
name: Bump Version

# FYI: Requires Personal Access Token. See README

on:
  push:
    branches: [main]
  workflow_dispatch: null # For manual runs

jobs:
  bump-version:
    # Ignore the commits from this action
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-22.04
    name: Bump version and make release with commitizen
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          branch: main
          changelog_increment_filename: body.md
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: body.md
          tag_name: ${{ env.REVISION }}
